# Book settings
title: The Reinforcement Learning Playground
logo: images/logo.png
author: Lars Quaedvlieg
email: larsquaedvlieg@outlook.com
copyright: "2022"

# Execution settings
execute:
  execute_notebooks: off  # Must be one of ("auto", "force", "cache", "off")
  allow_errors: false

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
  myst_dmath_double_inline: true

# HTML-specific settings
html:
  favicon: images/favicon.ico
  home_page_in_navbar: true
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: Powered by <a target="_blank" href="https://jupyterbook.org">Jupyter Book</a>
  baseurl: "https://lars-quaedvlieg.github.io/RL-Playground/"

# LaTeX-specific settings
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: false

repository:
  url: https://github.com/lars-quaedvlieg/RL-Playground
  path_to_book: docs
  branch: master

# References settings
bibtex_bibfiles:
  - references.bib

# Advanced settings
sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js